FLAG = -Wall -Werror
CPP = g++
CXX_FLAG = --std=c++11 -g

all: testbst

testbst: testbst.o intbst.o
	g++ $(CXX_FLAG) -o testbst testbst.o intbst.o

testbst.o: testbst.cpp
	g++ $(CXX_FLAG) testbst.cpp

intbst.o: intbst.cpp
	g++ $(CXX_FLAG) intbst.cpp

clean:
	rm -f testbst *.o
	